name: Run Playwright Tests

on:
  push:
    branches:
      - config-with-secrets
  workflow_dispatch:  # Позволяет запускать вручную из GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    env:
        BASE_URL: ${{ secrets.BASE_URL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        PRODUCT_PATH: ${{ secrets.PRODUCT_PATH }}
        CART_PATH: ${{ secrets.CART_PATH }}
        BROWSER: ${{ secrets.BROWSER }}
        HEADLESS: ${{ secrets.HEADLESS }}
        SLOW_MOTION: ${{ secrets.SLOW_MOTION }}
        TIMEOUT: ${{ secrets.TIMEOUT }}
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASS: ${{ secrets.USER_PASS }}
        USER_NAME_SESSION: ${{ secrets.USER_NAME_SESSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies with Gradle
        run: ./gradlew dependencies  # Устанавливаем все зависимости, включая Playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Check directory structure
        run: ls -la  # Проверяем, где находится build.gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew  # Даем права на выполнение Gradle wrapper

      - name: Run tests with Gradle
        run: |
          ./gradlew test \
            -Dbase.url="$BASE_URL" \
            -Ddomain="$DOMAIN" \
            -Dproduct.path="$PRODUCT_PATH" \
            -Dcart.path="$CART_PATH" \
            -Dbrowser="$BROWSER" \
            -Dheadless="$HEADLESS" \
            -Dslow.motion="$SLOW_MOTION" \
            -Dtimeout="$TIMEOUT" \
            -DuserName="$USER_NAME" \
            -DuserPass="$USER_PASS" \
            -DuserNameSession="$USER_NAME_SESSION"