name: Run Playwright Tests

on:
  push:
    branches:
      - config-with-secrets
  workflow_dispatch:  # Позволяет запускать вручную из GitHub Actions

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Playwright
        run: |
            npm install playwright@1.41.0
            npx playwright install
          
      - name: Check Playwright version and browsers
        run: |
          npx playwright --version
          npx playwright show-browsers

      - name: Check directory structure
        run: ls -la

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew  # Даем права на выполнение Gradle wrapper

      - name: Debug environment variables
        run: env | grep -E "BASE_URL|DOMAIN|PRODUCT_PATH|CART_PATH|BROWSER|HEADLESS|SLOW_MOTION|TIMEOUT|USER_NAME|USER_PASS|USER_NAME_SESSION"

      - name: Debug Java properties
        run: java -XshowSettings:properties -version

      - name: Run tests with Gradle
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          DOMAIN: ${{ secrets.DOMAIN }}
          PRODUCT_PATH: ${{ secrets.PRODUCT_PATH }}
          CART_PATH: ${{ secrets.CART_PATH }}
          BROWSER: ${{ secrets.BROWSER }}
          HEADLESS: ${{ secrets.HEADLESS }}
          SLOW_MOTION: ${{ secrets.SLOW_MOTION }}
          TIMEOUT: ${{ secrets.TIMEOUT }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASS: ${{ secrets.USER_PASS }}
          USER_NAME_SESSION: ${{ secrets.USER_NAME_SESSION }}
        run: |
          ./gradlew test